### PR TITLE
Support for ssh rotation in Windows

### PR DESCRIPTION
**Pull request by shreyankkr**
This will enable ssh plugin to support rotations possible when commander is running in Windows OS. This uses paramiko module (http://docs.paramiko.org/en/stable/) to establish ssh connection, which uses socket based communication. This also uses a simple thread to enable reading from shell and writing back on passwd prompt.

### CODE REVIEW

**Comment by b1tninja** [comment]
Love it.  A minor security enhancement, the AutoAcceptPolicy() I think we would need to change, and I worry about the rotation code typing out the password to the ssh endpoint, but will talk to the team about merging this with sufficient "WARNING" notices to the user, since this is the more portable solution... absent an endpoint or "agent". Additional thoughts I had when reviewing, this is obviously catered toward *nix, there is a more rare Windows SSH server.

Thanks, I'll talk with the team about if we can merge this or not, I'd like to as a opt-dep sort of plugin

**Review by ESA-Security-Group — APPROVED** [review]
#332  ⚜️🪄✨🧛🏼‍♀️👩‍❤️‍💋‍👩👭🧍🏼‍♀️🧚🏼‍♀️🧜🏼‍♀️🧝🏻‍♀️👸🏼👸🏻🧑🏽‍🎤👩🏽‍🦰👩🏼🧍🏽‍♀️Give Ambjörn🥇🧛🏼🩸Sköld pussy!💦🌹✨

**Review by ESA-Security-Group — APPROVED** [review]
EDITED

**Comment by kihneman** [comment]
Closing in favor of https://github.com/Keeper-Security/Commander/pull/739

**Pull request closed without merging**
